matrix:
  include:
    - dist: bionic
    - dist: xenial
    - dist: trusty
script:
  - /sbin/sysctl net.ipv6.conf.all.disable_ipv6
  - /sbin/sysctl net.ipv6.conf.default.disable_ipv6
  - cat /etc/hosts
