language: generic
os:
  - linux
  - osx
services:
  - docker
before_install:
  - docker pull ubuntu
script:
  - |
    docker run -v $PWD:/$TRAVIS_REPO_SLUG -it -w /$TRAVIS_REPO_SLUG ubuntu bash -c '
    echo 1
    '
