dist: bionic
os: linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y cpanminus libperl-dev perl
install:
    - cpanm --sudo -nq --installdeps https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.07-TRIAL.tar.gz
    - env HARNESS_VERBOSE=1 cpanm --verbose --no-interactive --reinstall --test-only --test-timeout=30 https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.07-TRIAL.tar.gz
perl:
    - "5.26"
script: true
