language: generic
services:
  - docker
before_install:
  - docker pull rakudo-star
  - docker run rakudo-star perl6 -v
script:
  - |
    docker run -v $PWD:/$TRAVIS_REPO_SLUG -it -w /$TRAVIS_REPO_SLUG rakudo-star bash -c '
    echo 1
    '
