dist: bionic
os: linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y cpanminus libperl-dev perl git net-tools
install:
    - perl -V
    - cpanm --sudo -nq --installdeps https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.07-TRIAL.tar.gz
    - git clone https://github.com/skaji/HTTP-Daemon
    - cd HTTP-Daemon && git checkout -q test && perl -Ilib t/chunked.t
perl:
    - "5.26"
script: true
