apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test4-app
  name: test4-app
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: test4-app
  template:
    metadata:
      labels:
        app: test4-app
    spec:
      containers:
        - image: index.docker.io/skaji/sandbox-spinnaker
          name: test4-app
          ports:
            - containerPort: 8080
              protocol: TCP
